-- YouTube数据分析系统数据库设计

-- 采集任务状态表
CREATE TABLE IF NOT EXISTS CrawlTasks (
    TaskId TEXT PRIMARY KEY,
    TaskType TEXT NOT NULL, -- 'keyword', 'channel', 'playlist', 'video'
    TargetId TEXT NOT NULL, -- 关键词、频道ID、播放列表ID等
    Status TEXT NOT NULL, -- 'pending', 'running', 'completed', 'failed', 'paused'
    TotalItems INTEGER DEFAULT 0,
    ProcessedItems INTEGER DEFAULT 0,
    StartTime DATETIME,
    EndTime DATETIME,
    LastProcessedId TEXT,
    ErrorMessage TEXT,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 频道信息表
CREATE TABLE IF NOT EXISTS Channels (
    ChannelId TEXT PRIMARY KEY,
    Title TEXT NOT NULL,
    Description TEXT,
    ThumbnailUrl TEXT,
    SubscriberCount INTEGER,
    VideoCount INTEGER,
    ViewCount INTEGER,
    IsVerified INTEGER DEFAULT 0,
    Country TEXT,
    CustomUrl TEXT,
    PublishedAt DATETIME,
    LastCrawled DATETIME DEFAULT CURRENT_TIMESTAMP,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 视频信息表
CREATE TABLE IF NOT EXISTS Videos (
    VideoId TEXT PRIMARY KEY,
    ChannelId TEXT NOT NULL,
    Title TEXT NOT NULL,
    Description TEXT,
    Duration INTEGER, -- 秒数
    UploadDate DATETIME,
    ViewCount INTEGER,
    LikeCount INTEGER,
    DislikeCount INTEGER,
    CommentCount INTEGER,
    Category TEXT,
    License TEXT,
    PrivacyStatus TEXT,
    ThumbnailUrl TEXT,
    Tags TEXT, -- JSON格式存储标签数组
    Keywords TEXT, -- 提取的关键词
    IsLiveContent INTEGER DEFAULT 0,
    IsAgeRestricted INTEGER DEFAULT 0,
    LastCrawled DATETIME DEFAULT CURRENT_TIMESTAMP,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ChannelId) REFERENCES Channels(ChannelId)
);

-- 流媒体信息表
CREATE TABLE IF NOT EXISTS VideoStreams (
    StreamId INTEGER PRIMARY KEY AUTOINCREMENT,
    VideoId TEXT NOT NULL,
    StreamType TEXT NOT NULL, -- 'audio', 'video', 'muxed'
    Container TEXT NOT NULL,
    Codec TEXT,
    QualityLabel TEXT,
    Bitrate INTEGER,
    Width INTEGER,
    Height INTEGER,
    FrameRate INTEGER,
    FileSize INTEGER,
    IsDefault INTEGER DEFAULT 0,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (VideoId) REFERENCES Videos(VideoId)
);

-- 字幕信息表
CREATE TABLE IF NOT EXISTS Captions (
    CaptionId INTEGER PRIMARY KEY AUTOINCREMENT,
    VideoId TEXT NOT NULL,
    LanguageCode TEXT NOT NULL,
    LanguageName TEXT,
    IsAutoGenerated INTEGER DEFAULT 0,
    CaptionContent TEXT, -- 字幕内容（可选存储）
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (VideoId) REFERENCES Videos(VideoId)
);

-- 播放列表表
CREATE TABLE IF NOT EXISTS Playlists (
    PlaylistId TEXT PRIMARY KEY,
    ChannelId TEXT,
    Title TEXT NOT NULL,
    Description TEXT,
    ThumbnailUrl TEXT,
    VideoCount INTEGER,
    PrivacyStatus TEXT,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ChannelId) REFERENCES Channels(ChannelId)
);

-- 播放列表视频关系表
CREATE TABLE IF NOT EXISTS PlaylistVideos (
    PlaylistId TEXT NOT NULL,
    VideoId TEXT NOT NULL,
    Position INTEGER NOT NULL,
    AddedAt DATETIME,
    PRIMARY KEY (PlaylistId, VideoId),
    FOREIGN KEY (PlaylistId) REFERENCES Playlists(PlaylistId),
    FOREIGN KEY (VideoId) REFERENCES Videos(VideoId)
);

-- 关键词搜索记录表
CREATE TABLE IF NOT EXISTS KeywordSearches (
    SearchId INTEGER PRIMARY KEY AUTOINCREMENT,
    Keyword TEXT NOT NULL,
    TotalResults INTEGER,
    SearchDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    IsCompleted INTEGER DEFAULT 0
);

-- 智能发现系统相关表
CREATE TABLE IF NOT EXISTS DiscoveryTasks (
    TaskId TEXT PRIMARY KEY,
    Seed TEXT NOT NULL,
    Source TEXT NOT NULL, -- 'Keyword', 'Channel', 'Video'
    Mode TEXT NOT NULL, -- 'BreadthFirst', 'DepthFirst'
    MaxDepth INTEGER DEFAULT 3,
    BranchingFactor INTEGER DEFAULT 5,
    MaxTotalItems INTEGER DEFAULT 1000,
    Status TEXT NOT NULL, -- 'pending', 'running', 'completed', 'failed', 'paused'
    ProcessedCount INTEGER DEFAULT 0,
    TotalProcessed INTEGER DEFAULT 0,
    QueueSize INTEGER DEFAULT 0,
    LastProcessedNode TEXT,
    ErrorMessage TEXT,
    StartTime DATETIME,
    EndTime DATETIME,
    LastUpdate DATETIME,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS DiscoveryNodes (
    NodeId TEXT PRIMARY KEY,
    TaskId TEXT NOT NULL,
    NodeType TEXT NOT NULL, -- 'Keyword', 'Channel', 'Video'
    Content TEXT NOT NULL,
    Depth INTEGER NOT NULL,
    DiscoveredCount INTEGER DEFAULT 0,
    ProcessedAt DATETIME,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (TaskId) REFERENCES DiscoveryTasks(TaskId)
);

CREATE TABLE IF NOT EXISTS DiscoveryEdges (
    EdgeId INTEGER PRIMARY KEY AUTOINCREMENT,
    TaskId TEXT NOT NULL,
    SourceNodeId TEXT NOT NULL,
    TargetNodeId TEXT NOT NULL,
    EdgeType TEXT NOT NULL, -- 'related', 'channel', 'keyword'
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (TaskId) REFERENCES DiscoveryTasks(TaskId),
    FOREIGN KEY (SourceNodeId) REFERENCES DiscoveryNodes(NodeId),
    FOREIGN KEY (TargetNodeId) REFERENCES DiscoveryNodes(NodeId)
);

-- 内容发现记录表
CREATE TABLE IF NOT EXISTS ContentDiscovery (
    DiscoveryId INTEGER PRIMARY KEY AUTOINCREMENT,
    SourceType TEXT NOT NULL, -- 'video', 'channel', 'keyword'
    SourceId TEXT NOT NULL,
    DiscoveredType TEXT NOT NULL,
    DiscoveredId TEXT NOT NULL,
    DiscoveryMethod TEXT NOT NULL, -- 'search', 'related', 'channel_upload', 'keyword_extract'
    ConfidenceScore REAL DEFAULT 1.0,
    DiscoveredAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 索引优化
CREATE INDEX IF NOT EXISTS idx_videos_channel ON Videos(ChannelId);
CREATE INDEX IF NOT EXISTS idx_videos_upload_date ON Videos(UploadDate);
CREATE INDEX IF NOT EXISTS idx_videos_view_count ON Videos(ViewCount);
CREATE INDEX IF NOT EXISTS idx_streams_video ON VideoStreams(VideoId);
CREATE INDEX IF NOT EXISTS idx_captions_video ON Captions(VideoId);
CREATE INDEX IF NOT EXISTS idx_playlist_videos ON PlaylistVideos(PlaylistId, Position);
CREATE INDEX IF NOT EXISTS idx_tasks_status ON CrawlTasks(Status);
CREATE INDEX IF NOT EXISTS idx_discovery_tasks_status ON DiscoveryTasks(Status);
CREATE INDEX IF NOT EXISTS idx_discovery_nodes_task ON DiscoveryNodes(TaskId);
CREATE INDEX IF NOT EXISTS idx_discovery_nodes_type ON DiscoveryNodes(NodeType);
CREATE INDEX IF NOT EXISTS idx_discovery_edges_task ON DiscoveryEdges(TaskId);
CREATE INDEX IF NOT EXISTS idx_content_discovery_source ON ContentDiscovery(SourceType, SourceId);
CREATE INDEX IF NOT EXISTS idx_content_discovery_discovered ON ContentDiscovery(DiscoveredType, DiscoveredId);